Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	10	gen_fastq
	1	require_fastq
	11

[Fri Mar 13 18:27:23 2020]
rule gen_fastq:
    input: ../../data/snATAC/fastq.demultiplex/DH_03_rep2/DH_03_rep2.R2.fastq.gz
    output: fastq.cluster/DH_03_rep2.1.R2.fastq.gz
    jobid: 7
    wildcards: tissue=DH_03, time_rep=rep2, rd=R2

Terminating processes on user request, this might take some time.
[Fri Mar 13 18:28:06 2020]
Error in rule gen_fastq:
    jobid: 7
    output: fastq.cluster/DH_03_rep2.1.R2.fastq.gz

RuleException:
CalledProcessError in line 28 of /mnt/tscc/yanxiao/projects/mouse_aging/scripts/repEnrich_analysis/Snakemake.RepEnrich2:
Command ' set -euo pipefail;  python ~/software/github/single-cell-utils/split_fastq_by_cluster.py --meta metaInfo/DH_03_rep2.meta.txt -i ../../data/snATAC/fastq.demultiplex/DH_03_rep2/DH_03_rep2.R2.fastq.gz --barcode-pos 2 --cluster-pos 9 --fastq-barcode-re '@(.*?):.*' --outPrefix fastq.cluster/DH_03_rep2 --outAffix R2.fastq.gz ' returned non-zero exit status 1.
  File "/mnt/tscc/yanxiao/projects/mouse_aging/scripts/repEnrich_analysis/Snakemake.RepEnrich2", line 28, in __rule_gen_fastq
  File "/projects/ps-renlab/yanxiao/software/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job gen_fastq since they might be corrupted:
fastq.cluster/DH_03_rep2.1.R2.fastq.gz
Complete log: /mnt/tscc/yanxiao/projects/mouse_aging/scripts/repEnrich_analysis/.snakemake/log/2020-03-13T182723.751161.snakemake.log
